In [20]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, cohen_kappa_score


In [21]:
main_df = pd.read_excel(r"")
print(main_df.columns)

Index(['글 자료 ID', 'C1', 'C1_responses_gpt3.5', 'C1_gpt3.5', 'C2',
       'C2_responses_gpt3.5', 'C2_gpt3.5', 'C3', 'C3_gpt3.5', 'C4',
       'C4_responses_gpt3.5', 'C4_gpt3.5', 'C5', 'C5_responses_gpt3.5',
       'C5_gpt3.5', 'O1', 'O1_responses_gpt3.5', 'O1_gpt3.5', 'O2',
       'O2_responses_gpt3.5', 'O2_gpt3.5', 'L1', 'L1_responses_gpt3.5',
       'L1_gpt3.5', 'L2', 'L2_responses_gpt3.5', 'L2_gpt3.5',
       'C5_revised_responses_gpt3.5', 'C5_revised_gpt3.5', 'Unnamed: 29',
       'Unnamed: 30', 'L1_format', 'L1_gpt3.5_format', 'L2_format',
       'L2_gpt3.5_format', 'Unnamed: 35', 'Unnamed: 36', 'C1_responses_gpt4',
       'C1_gpt4', 'C2_responses_gpt4', 'C2_gpt4', 'C2_forgpt4'],
      dtype='object')


In [78]:
print("Confusion Matrix of C1\n", confusion_matrix(main_df['C1'],main_df['C1_gpt3.5']),"\n")
print("QWK of C1: ",cohen_kappa_score(main_df['C1'],main_df['C1_gpt3.5'],weights= 'quadratic'))

print("Confusion Matrix of C2\n", confusion_matrix(main_df['C2'],main_df['C2_gpt3.5']),"\n")
print("QWK of C2: ",cohen_kappa_score(main_df['C2'],main_df['C2_gpt3.5'],weights= 'quadratic'))

print("Confusion Matrix of C3\n", confusion_matrix(main_df['C3'],main_df['C3_gpt3.5']),"\n")
print("QWK of C3: ",cohen_kappa_score(main_df['C3'],main_df['C3_gpt3.5'],weights= 'quadratic'))

print("Confusion Matrix of C4\n", confusion_matrix(main_df['C4'],main_df['C4_gpt3.5']),"\n")
print("QWK of C4: ",cohen_kappa_score(main_df['C4'],main_df['C4_gpt3.5'],weights= 'quadratic'))

print("Confusion Matrix of C5\n", confusion_matrix(main_df['C5'],main_df['C5_gpt3.5']),"\n")
print("QWK of C5: ",cohen_kappa_score(main_df['C5'],main_df['C5_gpt3.5'],weights= 'quadratic'))

print("Confusion Matrix of O1\n", confusion_matrix(main_df['O1'],main_df['O1_gpt3.5']),"\n")
print("QWK of O1: ",cohen_kappa_score(main_df['O1'],main_df['O1_gpt3.5'],weights= 'quadratic'))

print("Confusion Matrix of O2\n", confusion_matrix(main_df['O2'],main_df['O2_gpt3.5']),"\n")
print("QWK of O2: ",cohen_kappa_score(main_df['O2'],main_df['O2_gpt3.5'],weights= 'quadratic'))

main_df = main_df.dropna(subset=['L1_format', 'L1_gpt3.5_format'])

print("Confusion Matrix of L1\n", confusion_matrix(main_df['L1_format'],main_df['L1_gpt3.5_format']),"\n")
print("QWK of L1: ",cohen_kappa_score(main_df['L1_format'],main_df['L1_gpt3.5_format'],weights= 'quadratic'))

print("Confusion Matrix of L2\n", confusion_matrix(main_df['L2_format'],main_df['L2_gpt3.5_format']),"\n")
print("QWK of L2: ",cohen_kappa_score(main_df['L2_format'],main_df['L2_gpt3.5_format'],weights= 'quadratic'))

print("Confusion Matrix of C5_revised\n", confusion_matrix(main_df['C5'],main_df['C5_revised_gpt3.5']),"\n")
print("QWK of C5_revised: ",cohen_kappa_score(main_df['C5'],main_df['C5_revised_gpt3.5'],weights= 'quadratic'))

Confusion Matrix of C1
 [[ 0  3 12  4  0]
 [ 0 12 22 26  0]
 [ 0  9 29 54  0]
 [ 0  2 21 71  0]
 [ 0  1  4 28  0]] 

QWK of C1:  0.2940070940759172
Confusion Matrix of C2
 [[ 0  3  9  5  0]
 [ 0  7 19 17  0]
 [ 0  7 16 51  0]
 [ 0  3 29 57  0]
 [ 0  4 12 59  0]] 

QWK of C2:  0.22601783490761818
Confusion Matrix of C3
 [[ 0  4 14  4  0]
 [ 0 10 30 21  0]
 [ 0 11 36 37  0]
 [ 0  3 25 55  0]
 [ 0  1 12 35  0]] 

QWK of C3:  0.288488826919043
Confusion Matrix of C4
 [[ 0  1 15  9  0]
 [ 0  5 33 39  0]
 [ 0  3 34 53  0]
 [ 0  0 17 46  0]
 [ 0  0  8 35  0]] 

QWK of C4:  0.18435397078137172
Confusion Matrix of C5
 [[ 0  1 29 39  0]
 [ 0  3 18 49  0]
 [ 0  3 17 57  0]
 [ 0  0  4 51  0]
 [ 0  0  3 24  0]] 

QWK of C5:  0.10885576400945307
Confusion Matrix of O1
 [[ 0 11  5  4  0]
 [ 0 20 10 30  0]
 [ 0 14 19 51  0]
 [ 0  9 14 54  0]
 [ 0  5  4 48  0]] 

QWK of O1:  0.3130181467731161
Confusion Matrix of O2
 [[ 0  4 16  8  0]
 [ 0  4 21 30  0]
 [ 0  2 22 67  0]
 [ 0  0 14 59  0]
 [ 0  0  6 45 